### ISSUE TITLE
Bug: URLs converted to lowercase

### ISSUE THREAD

**Issue by antermin** [garywill/autoReferer#1]
When I left-click on links, the URL is converted to lowercase.

To reproduce:
1. Install the latest version (0.8.3) from [AMO](https://addons.mozilla.org/en-US/firefox/addon/auto-referer/versions/)
2. Search "JPEG XL" in DuckDuckGo
3. Left-click on the result which links to Wikipedia's article
4. The URL becomes `https://en.wikipedia.org/wiki/Jpeg_xl`, which causes Wikipedia to display "Wikipedia does not have an article with this exact name."

I find that by downgrading to 0.8.1, the issue will disappear.

However, it looks like this repository is still serving the old version of the code, so I am unable to see the commits between 0.8.1 and 0.8.3.

**Comment by garywill** [comment]
Hi, thank you for feedback. 

I don't have time to do tests currently, so I released 0.8.6 , which is same as 0.8.1, for reverting purpose, if 0.8.3 really has bugs.
I'll release new version after I get time to check the new code and make sure it functions correctly. 

I pushed 0.8.3 code in `dev` branch. If you find something bug please post it here
