### ISSUE TITLE
Bug: Addon does not encode the question mark properly, which breaks some URLs

### ISSUE THREAD

**Issue by antermin** [garywill/autoReferer#2]
For some URLs, e.g. Wikipedia articles with a question mark in the title, the `?` symbol has to be encoded to `%3F`, otherwise the URL will not be correct.

Case 1: Question mark at the end of title:
1. Install the latest version (0.8.21) from [AMO](https://addons.mozilla.org/en-US/firefox/addon/auto-referer/versions/)
2. Search "How Heavy Are the Dumbbells You Lift" in any search engine (I tested on DuckDuckGo.)
3. Click on the result which links to Wikipedia's article
4. The URL becomes `https://en.wikipedia.org/wiki/How_Heavy_Are_the_Dumbbells_You_Lift?`, which causes Wikipedia to display "Wikipedia does not have an article with this exact name."

Case 2: Question mark in the middle and at the end of title:
1. Visit `https://en.wikipedia.org/wiki/WorldEnd`
2. Click "日本語" on the left sidebar to go to the Japanese version
3. The URL becomes `https://ja.wikipedia.org/wiki/%E7%B5%82%E6%9C%AB%E3%81%AA%E3%81%AB%E3%81%97%E3%81%A6%E3%81%BE%E3%81%99%E3%81%8B?_%E5%BF%99%E3%81%97%E3%81%84%E3%81%A7%E3%81%99%E3%81%8B?_%E6%95%91%E3%81%A3%E3%81%A6%E3%82%82%E3%82%89%E3%81%A3%E3%81%A6%E3%81%84%E3%81%84%E3%81%A7%E3%81%99%E3%81%8B?`
4. In other words, the latter part of the URL becomes`終末なにしてますか?_忙しいですか?_救ってもらっていいですか?`, and Wikipedia displays "ウィキペディアには現在この名前の項目はありません。" (which means there is no such article)

In both cases, if I manually change `?` to `%3F`, then it works.

**Comment by garywill** [comment]
Thank you for feedback. Please try this:
[auto_referer-0.8.23.xpi.zip](https://github.com/garywill/autoReferer/files/10119969/auto_referer-0.8.23.xpi.zip)

If fixed on this 0.8.23, I'll release it to AMO tomorrow
